name: SAST Scan

on:
  push:
    branches:
      - '**' # Triggers on pushes to all branches
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:

jobs:
  sast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install SAST Tool (e.g., Bandit for Python projects)
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run SAST Scan
        run: |
          bandit -r . -f txt -o SAST_REPORT.txt || true

      - name: Update README.md with SAST Report
        run: |
          if grep -q "SAST REPORT" README.md; then
            sed -i "/SAST REPORT/r SAST_REPORT.txt" README.md
            sed -i "/SAST REPORT/d" README.md
          else
            echo "No placeholder 'SAST REPORT' found in README.md"
          fi

      - name: Commit Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md SAST_REPORT.txt
          if ! git diff --cached --quiet; then
            git commit -m "Update README.md with SAST Report"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.WOLFPACK_TOKEN }}
